es_proj/es_proj/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('picosage.urls')),
    path('admin/', admin.site.urls),
]

es_proj/picosage/urls.py
from django.urls import path

from . import views

app_name = 'picosage'
urlpatterns = [
    path('', views.index, name='index'),
    # All Properties
    path('properties/', views.properties_all, name='properties_all'),
    # Single Property
    path('properties/<int:property_id>/', views.property_single, name='property_details'),
]

es_proj/picosage/models.py
from django.db import models
from phone_field import PhoneField


# Inspiration from https://stackoverflow.com/questions/7700487/how-to-model-a-postal-address
class USAddress(models.Model):
    street = models.TextField()
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=11)

    def __str__(self):
        return f"{self.street} {self.city}, {self.state} {self.zip_code}"


class Consumer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = PhoneField()  # Using 3rd-party Model until it adds comlexity
    date_joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class Property(models.Model):
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE)
    # Reset db to get rid of null setting: https://stackoverflow.com/questions/42150499/how-do-i-delete-db-sqlite3-in-django-1-9-to-start-from-scratch/42150639
    address = models.ForeignKey(USAddress, on_delete=models.PROTECT, null=True)  # TODO: null-False
    annual_kwh = models.PositiveIntegerField()
    date_posted = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.consumer.first_name} {self.consumer.last_name} at {self.address.street}"


class Installer(models.Model):
    name = models.CharField(max_length=100)
    # Reset db to get rid of null setting: https://stackoverflow.com/questions/42150499/how-do-i-delete-db-sqlite3-in-django-1-9-to-start-from-scratch/42150639
    address = models.ForeignKey(USAddress, on_delete=models.PROTECT, null=True)  # TODO: null=False
    date_started = models.DateField(null=True)  # TODO: null=False
    date_joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    # Retain for analysis (subject to installer and Consumer privacy policy)
    installer = models.ForeignKey(Installer, null=True, on_delete=models.SET_NULL)
    property = models.ForeignKey(Property, null=True, on_delete=models.SET_NULL)
    cost = models.DecimalField(max_digits=11, decimal_places=2)
    panel_brand = models.CharField(max_length=100)
    panel_type = models.CharField(max_length=255)
    date_offered = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.installer.name} for {self.property.address.street}"

es_proj/picosage/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.template import loader

from .models import Consumer, Property, Installer, Quote


def index(request):
    return HttpResponse("Hello, world. You're at the picosage index.")


def properties_all(request):
    property_list = Property.objects.order_by('-date_posted')
    context = {
        'property_list': property_list,
    }
    return render(request, 'picosage/properties.html', context)


def property_single(request, property_id):
    _property = Property.objects.get(id=property_id)
    quote_list = Quote.objects.filter(property=_property.id)
    context = {
        'property': _property,
        'quote_list': quote_list
    }
    return render(request, 'picosage/property_details.html', context)

es_proj/picosage/templates/picosage/properties.html
<html>
    <head>
        <!-- Style lifted from W3schools tutorial: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_table_intro -->
        <style>
         table {
             font-family: arial, sans-serif;
             border-collapse: collapse;
             width: 100%;
         }

         td, th {
             border: 1px solid #dddddd;
             text-align: left;
             padding: 8px;
         }

         tr:nth-child(even) {
             background-color: #dddddd;
         }
        </style>
    </head>
    <body>
        {% if property_list %}
        <table>
            <tr>
                <th>ID</th>
                <th>Owner</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Date Joined</th>
                <th>Address</th>
                <th>Annual KWH</th>
                <th>Date Posted</th>
            </tr>
            {% for property in property_list %}
            <tr>
                <td><a href="{% url 'picosage:property_details' property.id %}">
                    {{ property.id }}</a>
                    <td>
                        {{ property.consumer.last_name }}, {{ property.consumer.first_name }}
                    </td>
                    <td>{{ property.consumer.email }}</td>
                    <td>{{ property.consumer.phone }}</td>
                    <td>{{ property.consumer.date_joined }}</td>
                    <td>{{ property.address }}</td>
                    <td>{{ property.annual_kwh }}</td>
                    <td>{{ property.date_posted }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>No properties are available.</p>
        {% endif %}
    </body>
</html>

es_proj/picosage/templates/picosage/property_details.html
<html>
    <head>
        <!-- Style lifted from W3schools tutorial: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_table_intro -->
        <style>
         table {
             font-family: arial, sans-serif;
             border-collapse: collapse;
             width: 100%;
         }

         td, th {
             border: 1px solid #dddddd;
             text-align: left;
             padding: 8px;
         }
        </style>
    </head>
    <body>
        {% if property %}
        <h2>Property</h2>
        <table>
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>Annual KWH</th>
                <th>Date Posted</th>
            </tr>
            <tr>
                <td>{{ property.id }}</td>
                <td>{{ property.address }}</td>
                <td>{{ property.annual_kwh }}</td>
                <td>{{ property.date_posted }}</td>
            </tr>
        </table>
        <h2>Owner</h2>
        <table>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Date Joined</th>
            </tr>
            <tr>
                <td>{{ property.consumer.id }}</td>
                <td>
                    {{ property.consumer.last_name }}, {{ property.consumer.first_name }}
                </td>
                <td>{{ property.consumer.email }}</td>
                <td>{{ property.consumer.phone }}</td>
                <td>{{ property.consumer.date_joined }}</td>
            </tr>
        </table>
        <h2>Quotes</h2>
        <table>
            <tr>
                <th>ID</th>
                <th>Installer</th>
                <th>Cost</th>
                <th>Panel Brand</th>
                <th>Panel Type</th>
                <th>Date Offered</th>
                <th>Date Updated</th>
            </tr>
            {% for quote in quote_list %}
            <tr>
                <td>{{ quote.id }}</td>
                <td>{{ quote.installer }}</td>
                <td>{{ quote.cost }}</td>
                <td>{{ quote.panel_brand }}</td>
                <td>{{ quote.panel_type }}</td>
                <td>{{ quote.date_offered }}</td>
                <td>{{ quote.date_updated }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>No properties are available.</p>
        {% endif %}
    </body>
</html>